# -*- coding: utf-8 -*-
"""final project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ieDw72Dj3kg1NJ7Zl3uxPF3V7J1PQCab
"""

# تثبيت مكتبة YOLOv5
!pip install yolov5

#استيراد المكتبة:
import yolov5
# استيراد قاعدة بيانات من roboflow  لمعرفة المزيد البحث باليوتيوب عن How to Download Datasets from Roboflow

# تحميل الملف المضغوط في جوجل كلوب وبعده تفتح الملف المضغوط بالكود
!unzip "/content/lalala.v1i.yolov5pytorch.zip"

#استنساخ مستودع YOLOv5
!git clone https://github.com/ultralytics/yolov5.git

# Commented out IPython magic to ensure Python compatibility.
#تغيير المسار (Directory):
# %cd yolov5

#تثبيت جميع المكتبات الضرورية لتشغيل YOLOv5
!pip install -r requirements.txt

# تدريب النموذج
#--img 640: يحدد حجم الصورة التي سيعالجها النموذج.
#--batch 16: يحدد عدد الصور التي يتم تدريبها في كل مرة.
#--epochs 50: يحدد عدد المرات التي سيمر فيها النموذج على مجموعة البيانات بأكملها. يمكنك زيادة هذا الرقم إذا لم تكن النتائج جيدة.
#--data '...': المسار إلى ملف data.yaml الخاص بك.
#--weights yolov5s.pt: يخبر النموذج ببدء التدريب باستخدام نموذج YOLOv5s الذي تم تدريبه مسبقًا. هذا يوفر وقتًا وجهدًا كبيرًا في التدريب.
!python train.py --img 640 --batch 16 --epochs 50 --data '/content/data.yaml' --weights yolov5s.pt

# يجب أن تكون مستعد في كتابة رقم 3 قبل إنتهاء 3 ثواني في المخرجات لأنه سيعطيك 3 خيارات ونحن نحتاج رقم 3

#!python detect.py: هذا هو الأمر الذي يشغل ملف detect.py المسؤول عن الكشف عن الكائنات.
#--weights: يشير إلى مسار النموذج المدرب (best.pt).
#-img 640: يحدد حجم الصورة
#--conf 0.25: يحدد مستوى الثقة (confidence) للكشف. يمكنك زيادة هذا الرقم إذا كان النموذج يكتشف أشياء غير صحيحة، أو تقليله إذا كان يفوت بعض الكائنات
#-source: يشير إلى مسار الصورة التي تريد اختبار النموذج عليها
#بما أن التدريب لم يكتمل، سنستخدم ملف last.pt وليس best.pt. ملف last.pt هو النموذج الذي تم حفظه في آخر دورة تدريبية قبل التوقف، وهو النموذج الذي سنختبره. وقد انهى فقط 22
!python detect.py --weights /content/yolov5/runs/train/exp/weights/last.pt --img 640 --conf 0.25 --source "/content/منزل.04.17 PM.jpeg"
# حينحفظ في ملف yolov5

!wget -P /content/yolov5/weights https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s.pt

!python /content/yolov5/detect.py --weights /content/yolov5/weights/yolov5s.pt --source "/content/منزل.04.17 PM.jpeg" --name fresh_test